(()=>{'use strict';
const $=id=>document.getElementById(id);const SUPABASE_URL='https://lfdmbkzghnwvsapxypvt.supabase.co';const KEY='sb_publishable_bRnkA6PA8-v073nrw9zxiQ_8rVGiOn1';const SESSION='movida-cem-session';const ATTEMPTS='movida-cem-attempts';
const scenarios={transformer:{name:'Centro de transformación',description:'Inspección próxima a transformadores y barras de 50 Hz. Predomina el campo magnético de frecuencia industrial.',probe:'eh10m',q:'B',f:50,v:68,unit:'µT',harm:[.1,.04,.65,.08,.03,.02,.01,.01,.01,.01,.01,.01]},welding:{name:'Soldadura por resistencia',description:'Pulsos intensos y no sinusoidales. El promedio RMS por sí solo puede ocultar la complejidad temporal.',probe:'eh10m',q:'B',f:50,v:142,unit:'µT',harm:[.18,.12,.8,.35,.18,.1,.06,.04,.03,.02,.01,.01]},induction:{name:'Calentamiento por inducción',description:'Fuente industrial de frecuencia intermedia. La selección de banda y el análisis espectral son esenciales.',probe:'eh10m',q:'H',f:10000,v:28,unit:'A/m',harm:[.02,.04,.05,.06,.08,.12,.18,.28,.9,.22,.08,.04]},mri:{name:'Entorno de resonancia magnética',description:'Campo magnético estático muy intenso con gradientes espaciales. Requiere sonda DC específica y control de implantes.',probe:'static',q:'B',f:0,v:210,unit:'mT',harm:[.95,.01,.01,.01,.01,.01,.01,.01,.01,.01,.01,.01]},antenna:{name:'Mantenimiento de antenas',description:'Radiofrecuencia cerca de sistemas radiantes. La sonda E de alta frecuencia es la opción didáctica adecuada.',probe:'efield',q:'E',f:900000000,v:34,unit:'V/m',harm:[.02,.03,.04,.05,.08,.12,.15,.3,.55,.95,.4,.15]}};
const steps=[
{title:'Inspecciona y enciende',text:'Comprueba integridad, batería y vigencia de calibración; luego enciende.',why:'Una lectura no es defendible si el sistema de medición no está en condiciones.',action:'Encender equipo',do:'power'},
{title:'Reconoce la fuente',text:'Revisa el escenario, frecuencia probable, régimen de trabajo y posición del trabajador.',why:'La fuente determina qué magnitud, sonda, banda y método necesitas.',action:'Confirmar escenario',do:'scenario'},
{title:'Selecciona la sonda',text:'Escoge una sonda compatible con la magnitud y el intervalo de frecuencia esperado.',why:'Una sonda fuera de banda puede mostrar un número creíble pero incorrecto.',action:'Elegir sonda sugerida',do:'probe'},
{title:'Configura magnitud y banda',text:'Define E, H o B y usa la banda más adecuada sin excluir componentes relevantes.',why:'E y H/B no se sustituyen entre sí en campo cercano; la banda condiciona la señal capturada.',action:'Aplicar configuración',do:'configure'},
{title:'Realiza la puesta a cero',text:'Aléjate de la fuente y ejecuta la puesta a cero con la sonda estable.',why:'Reduce el sesgo instrumental y evita atribuir el fondo a la fuente evaluada.',action:'Puesta a cero',do:'zero'},
{title:'Mide con RMS verdadero',text:'Ubica la sonda en la posición del cuerpo, evita perturbar el campo y comienza la lectura.',why:'El RMS describe el valor eficaz; conserva distancia, orientación y tiempo representativos.',action:'Iniciar medición',do:'measure'},
{title:'Explora la FFT',text:'Cambia a FFT para identificar la frecuencia dominante y armónicos.',why:'Los límites dependen de la frecuencia y una señal compleja exige conocer su composición.',action:'Mostrar FFT',do:'fft'},
{title:'Evalúa con WPM',text:'Aplica WPM y compara el índice con el criterio seleccionado.',why:'El método pondera cada componente frente a su límite; 100 % exige una evaluación más detallada.',action:'Calcular WPM',do:'wpm'}];
let state={on:false,zero:false,measuring:false,mode:'guided',step:0,timer:null,measurement:null};
function msg(t,type=''){const el=$('actionMessage');el.textContent=t;el.className='action-message '+type}function toast(t){$('toast').textContent=t;$('toast').classList.add('show');setTimeout(()=>$('toast').classList.remove('show'),2200)}
function setLogin(t){$('loginMessage').textContent=t}function openApp(member,persist=true){const name=[member?.nombres,member?.apellidos].filter(Boolean).join(' ')||member?.name||'integrante';const expiresAt=member?.expiresAt||Date.now()+20*60e3;if(persist)sessionStorage.setItem(SESSION,JSON.stringify({name,expiresAt}));$('memberName').textContent=name;$('loginGate').hidden=true;$('appShell').hidden=false;document.body.classList.remove('auth-locked');renderScenario();renderGuide();setTimeout(()=>logout(true),Math.max(0,expiresAt-Date.now()))}
function logout(expired=false){clearInterval(state.timer);sessionStorage.removeItem(SESSION);$('appShell').hidden=true;$('loginGate').hidden=false;document.body.classList.add('auth-locked');$('memberLogin').reset();setLogin(expired?'Tu sesión de 20 minutos finalizó. Ingresa nuevamente.':'Sesión cerrada.');$('memberId').focus()}
async function login(e){e.preventDefault();const cedula=$('memberId').value.replace(/\D/g,''),codigo=$('memberPassword').value.trim();if(!cedula||!codigo){setLogin('Escribe tu cédula y tu clave para continuar.');return}const blocked=JSON.parse(localStorage.getItem(ATTEMPTS)||'{"count":0,"until":0}');if(blocked.until>Date.now()){setLogin('Demasiados intentos. Espera unos minutos.');return}const btn=$('loginSubmit');btn.disabled=true;btn.querySelector('span').textContent='Verificando…';try{const r=await fetch(`${SUPABASE_URL}/rest/v1/rpc/acceso_integrante`,{method:'POST',headers:{apikey:KEY,Authorization:`Bearer ${KEY}`,'Content-Type':'application/json'},body:JSON.stringify({p_cedula:cedula,p_codigo:codigo})});if(!r.ok)throw Error(r.status);const p=await r.json(),m=Array.isArray(p)?p[0]:p;if(!m){const count=(blocked.count||0)+1,lock=count>=5;localStorage.setItem(ATTEMPTS,JSON.stringify({count:lock?0:count,until:lock?Date.now()+15*60e3:0}));setLogin(lock?'Cinco intentos fallidos. Acceso pausado por 15 minutos.':`Datos no validados. Revisa cédula y clave; quedan ${5-count} intentos.`);return}localStorage.removeItem(ATTEMPTS);openApp(m);toast('Acceso validado')}catch(err){console.error(err);setLogin('El servicio de acceso no está disponible. Intenta nuevamente en unos minutos.')}finally{btn.disabled=false;btn.querySelector('span').textContent='Abrir simulador'}}
function formatFreq(f){if(f===0)return'0 Hz · DC';if(f>=1e6)return`${f/1e6} MHz`;if(f>=1e3)return`${f/1e3} kHz`;return`${f} Hz`}
function renderScenario(){const s=scenarios[$('scenarioSelect').value];$('scenarioName').textContent=s.name;$('scenarioDescription').textContent=s.description;$('frequency').textContent=formatFreq(s.f);if(!state.measurement){$('freqResult').textContent='—'}msg(state.on?'Selecciona la sonda adecuada para el escenario.':'Enciende el instrumento para comenzar.')}
function renderGuide(){const s=steps[state.step];$('stepNumber').textContent=`PASO ${state.step+1} DE ${steps.length}`;$('progressBar').style.width=`${(state.step+1)/steps.length*100}%`;$('guideIcon').textContent=String(state.step+1).padStart(2,'0');$('guideTitle').textContent=s.title;$('guideText').textContent=s.text;$('guideWhy').textContent=s.why;$('guideAction').textContent=s.action;$('prevStep').disabled=state.step===0;$('nextStep').disabled=state.step===steps.length-1}
function power(){state.on=!state.on;$('meter').classList.toggle('on',state.on);$('screen').classList.toggle('off',!state.on);$('statusChip').textContent=state.on?'ENCENDIDO':'APAGADO';$('statusChip').classList.toggle('ready',state.on);if(!state.on){state.zero=false;stopMeasure();resetDisplay();msg('Equipo apagado. Enciéndelo antes de configurar.')}else{msg('Autocomprobación correcta. Ahora reconoce la fuente y selecciona la sonda.','success');toast('Equipo listo')}}
function resetDisplay(){$('reading').textContent='--.--';$('axisX').textContent=$('axisY').textContent=$('axisZ').textContent='--';$('percent').textContent='-- % límite'}
function selectSuggested(){const s=scenarios[$('scenarioSelect').value];$('probeSelect').value=s.probe;probeChanged()}
function probeChanged(){const p=$('probeSelect').value,s=scenarios[$('scenarioSelect').value];const names={none:'Sin sonda',eh10m:'CEM–10M',efield:'E–60G',static:'DC–MAG'};$('probeBadge').textContent=names[p];$('probeHelp').textContent=p==='none'?'Selecciona una sonda antes de medir.':p===s.probe?'Sonda compatible con la magnitud y frecuencia de este escenario.':'Atención: esta sonda no es la recomendada para la fuente activa.';$('probe').style.opacity=p==='none'?'.42':'1'}
function configure(){const s=scenarios[$('scenarioSelect').value];$('quantitySelect').value=s.q;$('bandSelect').value=s.f<=400000?'low':'full';$('viewSelect').value='RMS';updateMode();msg('Magnitud, banda y RMS configurados para el escenario.','success')}
function zero(){if(!state.on)return msg('No puedes hacer la puesta a cero con el equipo apagado. Enciéndelo primero.','error');if($('probeSelect').value==='none')return msg('Conecta una sonda antes de hacer la puesta a cero.','error');state.zero=true;msg('Puesta a cero completada. Mantén la sonda estable y evita objetos metálicos próximos.','success');toast('Cero establecido')}
function validate(){const s=scenarios[$('scenarioSelect').value],p=$('probeSelect').value,q=$('quantitySelect').value;if(!state.on)return'Enciende el instrumento antes de medir.';if(p==='none')return'Selecciona una sonda. El instrumento no puede medir sin sensor.';if(p!==s.probe)return`La sonda seleccionada no cubre adecuadamente este escenario. Usa ${s.probe==='eh10m'?'CEM–10M':s.probe==='efield'?'E–60G':'DC–MAG'}.`;if(q!==s.q)return`Para este ejercicio selecciona ${s.q}; la magnitud actual no corresponde al objetivo.`;if(!state.zero)return'Realiza la puesta a cero antes de medir para controlar el sesgo instrumental.';return''}
function measure(){const error=validate();if(error)return msg(error,'error');if(state.measuring){stopMeasure();msg('Medición pausada. Puedes revisar o guardar el resultado.');return}state.measuring=true;$('measureBtn').textContent='Pausar medición';const s=scenarios[$('scenarioSelect').value];let tick=0;state.timer=setInterval(()=>{tick++;const jitter=(Math.sin(tick*.7)+Math.random()-.5)*s.v*.035;const val=Math.max(0,s.v+jitter);renderReading(val,s);state.measurement={value:val,f:s.f,wpm:calcWpm(val,s),unit:s.unit};renderResults()},380);msg('Midiendo… conserva la posición de la sonda y observa la estabilidad.','success')}
function stopMeasure(){state.measuring=false;clearInterval(state.timer);state.timer=null;$('measureBtn').textContent='Iniciar medición'}
function calcWpm(v,s){const base={transformer:100,welding:100,induction:60,mri:200,antenna:61}[Object.keys(scenarios).find(k=>scenarios[k]===s)]||100;const criterionFactor={eu:1,icnirp:1.06,public:5}[$('criterionSelect').value]||1;const complexity=s===scenarios.welding?1.18:1;return v/base*100*complexity*criterionFactor}
function renderReading(v,s){$('reading').textContent=v<10?v.toFixed(2):v.toFixed(1);$('unit').textContent=s.unit;$('axisX').textContent=(v*.61).toFixed(1);$('axisY').textContent=(v*.54).toFixed(1);$('axisZ').textContent=(v*.58).toFixed(1);$('percent').textContent=`${calcWpm(v,s).toFixed(0)} % límite`;renderSpectrum(s)}
function renderSpectrum(s){$('spectrum').innerHTML=s.harm.map((v,i)=>`<i style="height:${Math.max(4,v*100)}%" title="Componente ${i+1}"></i>`).join('')}
function renderResults(){const m=state.measurement;if(!m)return;m.wpm=calcWpm(m.value,scenarios[$('scenarioSelect').value]);$('rmsResult').textContent=`${m.value.toFixed(m.value<10?2:1)} ${m.unit}`;$('freqResult').textContent=formatFreq(m.f);$('wpmResult').textContent=`${m.wpm.toFixed(0)} %`;const safe=m.wpm<100;$('verdict').textContent=safe?'Por debajo del criterio':'Requiere acción';$('verdictText').textContent=safe?'Resultado didáctico inferior al 100 %':'Supera 100 %: verifica, delimita y controla';$('verdictCard').className=safe?'safe':'alert'}
function updateMode(){const v=$('viewSelect').value,q=$('quantitySelect').value;$('screenMode').textContent=`${v} · ${q}`;if(v==='FFT'&&state.measurement){renderSpectrum(scenarios[$('scenarioSelect').value]);msg('FFT activa: identifica la componente dominante y posibles armónicos.','success')}if(v==='WPM'&&state.measurement)msg('WPM activo: el porcentaje integra la señal frente al criterio seleccionado.','success')}
function guideAction(){const d=steps[state.step].do;if(d==='power'&&!state.on)power();if(d==='scenario')renderScenario();if(d==='probe')selectSuggested();if(d==='configure')configure();if(d==='zero')zero();if(d==='measure'&&!state.measuring)measure();if(d==='fft'){$('viewSelect').value='FFT';updateMode()}if(d==='wpm'){$('viewSelect').value='WPM';updateMode()}if(state.step<steps.length-1){state.step++;renderGuide()}}
document.addEventListener('DOMContentLoaded',()=>{const ses=JSON.parse(sessionStorage.getItem(SESSION)||'null');if(ses?.expiresAt>Date.now())openApp(ses,false);else $('memberId').focus();$('memberLogin').addEventListener('submit',login);$('togglePassword').onclick=()=>{const i=$('memberPassword');i.type=i.type==='password'?'text':'password';$('togglePassword').textContent=i.type==='password'?'Mostrar':'Ocultar'};$('logoutBtn').onclick=()=>logout(false);$('powerBtn').onclick=power;$('scenarioSelect').onchange=()=>{state.zero=false;stopMeasure();state.measurement=null;resetDisplay();renderScenario()};$('probeSelect').onchange=probeChanged;$('zeroBtn').onclick=zero;$('measureBtn').onclick=measure;$('quantitySelect').onchange=updateMode;$('viewSelect').onchange=updateMode;$('guideAction').onclick=guideAction;$('prevStep').onclick=()=>{state.step=Math.max(0,state.step-1);renderGuide()};$('nextStep').onclick=()=>{state.step=Math.min(steps.length-1,state.step+1);renderGuide()};document.querySelectorAll('.mode').forEach(b=>b.onclick=()=>{document.querySelectorAll('.mode').forEach(x=>x.classList.remove('active'));b.classList.add('active');state.mode=b.dataset.mode;$('guidedCard').hidden=state.mode==='free';toast(state.mode==='guided'?'Modo guiado activo':'Práctica libre activa')});$('conceptBtn').onclick=()=>$('conceptDialog').showModal();document.querySelector('.dialog-close').onclick=()=>$('conceptDialog').close();document.querySelectorAll('.softkeys button').forEach(b=>b.onclick=()=>{if(!state.on)return msg('El equipo está apagado.','error');if(b.dataset.key==='mode'){$('viewSelect').selectedIndex=($('viewSelect').selectedIndex+1)%3;updateMode()}else if(b.dataset.key==='save')toast(state.measurement?'Lectura guardada en memoria simulada':'Aún no hay una lectura para guardar');else if(b.dataset.key==='hold'){if(state.measuring)stopMeasure();toast('Lectura retenida')}})});
})();
